#!/bin/sh

ifconfig eth0 down
ifconfig wlan0 up
killall wpa_supplicant
wpa_supplicant -B -Dwext -iwlan0 -c/etc/wpa_supplicant.conf
sleep 3s
#static ip
#ifconfig wlan0 192.168.134.250 netmask 255.255.255.0
#route add default gw 192.168.134.1

killall udhcpc
udhcpc -b -i wlan0
